### ISSUE TITLE
What is this IP address in the config?

### ISSUE THREAD

**Issue by MauriceMahan** [just-team/react-native-youtube-player#1]
In ./src/config/index.js there a variable called API_URL:

    API_URL: "http://52.232.85.160/api?vid=",

Where did this IP address come from and where is the documentation on it? It appears to convert Youtube videos to mp3 but how did you even find this?

**Comment by var77** [comment]
Hi, thanks for comment. It's my https://github.com/var77/youtube-audio project running on the server
